spring:
  application:
    name: inventory-service

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      auto-offset-reset: earliest